name: Manual Auto Release

on:
  workflow_dispatch:  # 手动触发

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史和 tag

      - name: Get latest release tag
        id: get_latest_tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git tag --sort=-v:refname | head -n 1)
          if [[ -z "$LATEST_TAG" ]]; then
            NEW_TAG="v1.0.0"
          else
            VERSION=${LATEST_TAG#v}
            IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
            PATCH=$((PATCH + 1))
            NEW_TAG="v$MAJOR.$MINOR.$PATCH"
          fi
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "Latest tag: $LATEST_TAG"
          echo "Next tag: $NEW_TAG"

      - name: Zip files cleanly (excluding .git, .github, dist)
        run: |
          mkdir -p dist
          find . -type f \
            ! -path "./.git/*" \
            ! -path "./.github/*" \
            ! -path "./dist/*" \
            ! -name "*.zip" \
            | zip -@ ./dist/source.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_TAG }}
          name: ${{ env.NEW_TAG }}
          files: ./dist/source.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
