name: Manual Release

on:
  workflow_dispatch:  # 手动触发

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up variables
        id: vars
        run: |
          TAG_NAME="release-$(date +'%Y%m%d-%H%M%S')"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "Release tag: $TAG_NAME"

      - name: Zip files excluding .github directory
        run: |
          mkdir -p dist
          zip -r ./dist/source.zip . -x ".github/*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.TAG_NAME }}
          files: ./dist/source.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

